services:
  dhcp-agent-4:
    image: alexlanu/dhcp-app:1.2
    container_name: dhcp-agent-4

    environment:
      - DHCP_INT=eth0
      - DHCP_ALLOW_IP=192.168.1.32,192.168.1.50

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dhcp.out:/app/dhcp4.out:rw

    network_mode: "host"

    command: "/app/entrypoint.sh"

    privileged: true
    pid: "host"

    tmpfs: /tmp
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 256M
        reservations:
          cpus: '0.5'
          memory: 128M

    stop_grace_period: 5s
    restart: "${RESTART_POLICY}"

    labels:
      ru.prosoft.company: "Prosoft Ltd."
      ru.prosoft.component: "Python Agent"
